# Single source of target availability shared with the public Python registry.
set(GDN_QSA_TARGET "" CACHE STRING "GDN target; empty keeps the legacy build selection")
set(GDN_QSA_RESOLVED_TARGET "${GDN_QSA_TARGET}")
if(NOT GDN_QSA_RESOLVED_TARGET)
  if(GDN_QSA_ENABLE_PPU)
    set(GDN_QSA_RESOLVED_TARGET ppu10)
  else()
    set(GDN_QSA_RESOLVED_TARGET none)
  endif()
endif()
if(GDN_QSA_RESOLVED_TARGET STREQUAL "ppu10")
  if(DEFINED ACOMPUTE_VERSION AND NOT ACOMPUTE_VERSION STREQUAL "10000")
    message(FATAL_ERROR "legacy PPU1.0 target conflicts with ACOMPUTE_VERSION=${ACOMPUTE_VERSION}")
  endif()
  if(DEFINED CUTLASS_PPU_ARCHS AND NOT CUTLASS_PPU_ARCHS STREQUAL "ppu0010")
    message(FATAL_ERROR "legacy PPU1.0 target conflicts with CUTLASS_PPU_ARCHS=${CUTLASS_PPU_ARCHS}")
  endif()
endif()
if(GDN_QSA_ENABLE_PPU AND NOT GDN_QSA_RESOLVED_TARGET STREQUAL "ppu10")
  message(FATAL_ERROR "GDN_QSA_ENABLE_PPU is the legacy PPU1.0 alias, not ${GDN_QSA_RESOLVED_TARGET}")
endif()

file(READ "${CMAKE_CURRENT_LIST_DIR}/../actlize_la/backends/targets.json" _gdn_catalog)
set_property(DIRECTORY APPEND PROPERTY CMAKE_CONFIGURE_DEPENDS
  "${CMAKE_CURRENT_LIST_DIR}/../actlize_la/backends/targets.json")
string(JSON _gdn_schema GET "${_gdn_catalog}" schema)
if(NOT _gdn_schema EQUAL 1)
  message(FATAL_ERROR "unsupported GDN backend catalog schema")
endif()
string(JSON _gdn_target_count LENGTH "${_gdn_catalog}" targets)
math(EXPR _gdn_target_last "${_gdn_target_count}-1")
set(_gdn_choices "" none)
foreach(_gdn_index RANGE 0 ${_gdn_target_last})
  string(JSON _gdn_name MEMBER "${_gdn_catalog}" targets ${_gdn_index})
  list(APPEND _gdn_choices "${_gdn_name}")
endforeach()
set_property(CACHE GDN_QSA_TARGET PROPERTY STRINGS ${_gdn_choices})
if(NOT GDN_QSA_RESOLVED_TARGET STREQUAL "none")
  string(JSON _gdn_implemented ERROR_VARIABLE _gdn_error
    GET "${_gdn_catalog}" targets "${GDN_QSA_RESOLVED_TARGET}" implemented)
  if(_gdn_error)
    message(FATAL_ERROR "unknown GDN target: ${GDN_QSA_RESOLVED_TARGET}")
  endif()
  if(NOT _gdn_implemented)
    string(JSON _gdn_reason GET "${_gdn_catalog}" targets "${GDN_QSA_RESOLVED_TARGET}" reason)
    message(FATAL_ERROR "GDN target ${GDN_QSA_RESOLVED_TARGET}: ${_gdn_reason}")
  endif()
  string(JSON _gdn_build GET "${_gdn_catalog}" targets "${GDN_QSA_RESOLVED_TARGET}" build)
  if(NOT _gdn_build STREQUAL "cmake")
    message(FATAL_ERROR "GDN ${GDN_QSA_RESOLVED_TARGET} uses ${_gdn_build}, not the PPU CMake build")
  endif()
  string(JSON _gdn_dependency GET "${_gdn_catalog}" targets "${GDN_QSA_RESOLVED_TARGET}" dependency)
  get_filename_component(GDN_QSA_DEPENDENCY_ROOT
    "${CMAKE_CURRENT_LIST_DIR}/../${_gdn_dependency}" ABSOLUTE)
  string(JSON _gdn_entry ERROR_VARIABLE _gdn_entry_error
    GET "${_gdn_catalog}" targets "${GDN_QSA_RESOLVED_TARGET}" build_entry)
  if(_gdn_entry_error)
    message(FATAL_ERROR "GDN target ${GDN_QSA_RESOLVED_TARGET}: no registered build entry")
  endif()
  get_filename_component(GDN_QSA_BACKEND_ENTRY "${CMAKE_CURRENT_LIST_DIR}/../${_gdn_entry}" ABSOLUTE)
  if(NOT EXISTS "${GDN_QSA_BACKEND_ENTRY}")
    message(FATAL_ERROR "GDN target ${GDN_QSA_RESOLVED_TARGET}: missing build entry")
  endif()
endif()
if(DEFINED GDN_QSA_CONFIGURED_TARGET AND
   NOT GDN_QSA_CONFIGURED_TARGET STREQUAL GDN_QSA_RESOLVED_TARGET)
  message(FATAL_ERROR "GDN target changed in an existing build directory; use a separate target build directory")
endif()
set(GDN_QSA_CONFIGURED_TARGET "${GDN_QSA_RESOLVED_TARGET}" CACHE INTERNAL "GDN build identity")
message(STATUS "GDN backend source graph: ${GDN_QSA_RESOLVED_TARGET}")
